# This file is part of Grust, GObject introspection bindings for Rust
#
# Copyright (C) 2013, 2015  Mikhail Zabaluev <mikhail.zabaluev@gmail.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301  USA

# Taken from g-ir-scanner executable, to make Transformer work.
import os
import __builtin__
if os.name == 'nt':
    datadir = os.path.join(os.path.dirname(__file__), '..', 'share')
else:
    datadir = "/usr/share"
__builtin__.__dict__['DATADIR'] = datadir

from giscanner.transformer import Transformer
import argparse
import re
import string
import sys

def _init_templates(**kvargs):
    templates = {}
    for k, v in kvargs.iteritems():
        templates[k] = string.Template(string.lstrip(v, '\r\n'))
    return templates

def _sanitize_crate_name(name):
    return re.sub(r'\W', '_', name).lower()

def _sys_crate_name(namespace):
    """Derive a sys crate name from GIR data."""
    name = _sanitize_crate_name(namespace.name)
    name += '_'
    name += _sanitize_crate_name(namespace.version)
    return name + '_sys';

class SysCrateGenerator(object):
    """Generator for -sys crates."""

    templates = _init_templates(
        crate_prolog =
'''
// This file is generated by grust-gen

#![crate_name = "$crate_name"]
#![crate_type = "lib"]
''',
    )

    def __init__(self, transformer, output, options):
        self._transformer = transformer
        self._output = output
        self._options = options

    def _write_subst(self, template, **kvargs):
        self._output.write(template.substitute(kvargs))

    def generate(self):
        self._gen_crate_prolog()

    def _gen_crate_prolog(self):
        options = self._options
        name = (options.crate_name or
                _sys_crate_name(self._transformer.namespace))
        self._write_subst(self.templates['crate_prolog'], crate_name=name)

def _create_arg_parser():
    parser = argparse.ArgumentParser(
        description='Generate a Rust crate from GIR XML')
    parser.add_argument('girfile', help='GIR XML file')
    parser.add_argument('--sys', dest='sys_mode', action='store_true',
                        help='generate a sys crate')
    parser.add_argument('-o', '--output', type=argparse.FileType('w'),
                        help='output file')
    parser.add_argument('-I', '--include-dir', action='append',
                        dest='include_dirs', metavar='DIR',
                        help='add directory to include search path')
    parser.add_argument('--crate-name',
                        help='Name of the generated crate')
    return parser

if __name__ == '__main__':
    arg_parser = _create_arg_parser()
    args = arg_parser.parse_args()
    output = args.output
    if not args.sys_mode:
        sys.exit('only --sys mode is currently supported')
    if output is None:
        output = open('lib.rs', 'w')
    transformer = Transformer.parse_from_gir(args.girfile, args.include_dirs)
    gen = SysCrateGenerator(transformer, output, args)
    gen.generate()

